### ISSUE TITLE
Get 3d keypoints from outputs

### ISSUE THREAD

**Issue by alonelysnake** [xiyichen/smplify-x-partial#1]
@xiyichen 
Hi, I'm trying to extract 3d keypoints from the output and using to generate .bvh file, and I encounter several questioins below:
1. I noticed that 19 points from Expose and 2 points from PIXIE are used as the output, and the results contain 21*3 parameters in the key 'body_pose', but what is the correspondence and hierarchy between the output index and joints?
2. Is the parameters in 'body_pose' about the parent joint or about the root joint? If about parent joint, is it relative to the prior pose?
3. There's a key 'global_orient' in the output. I guess it relates to the global coordinate of the root. What does it actually mean and how can I use it to get the global location?
Many thanks in advance!

**Comment by xiyichen** [comment]
Hi @alonelysnake,
Thank you for your interest in our work. I believe these questions are more about SMPL-X, and I have found some references for them:
1. SMPL-X has 21 body joints in axis-angle representation. For the correspondences you can check out [here](https://github.com/vchoutas/smplify-x/issues/58). We initialize the first 19 joints from ExPose (L_Hip to R_Elbow) and the last 2 joints from PIXIE (L_Wrist and R_Wrist).
2. In SMPL-X the 0th joint (Pelvis) is the root, which I think is eqivalent to the global orientation (check out page 34 [here](https://files.is.tue.mpg.de/black/talks/SMPL-made-simple-FAQs.pdf)). All other joints are relative to it. We initialize both global orientation and body poses from results of the regression methods. Good point, we should've done a pelvis normalization for the body pose prior, but I believe the effects should be minor since the global orient only changes slightly during the optimization.
3. The 'global_orient' vector only describes the rotation of the body model in the world coordinates. You can find more details about how to change parameters to new coordinates [here](https://www.dropbox.com/scl/fi/zkatuv5shs8d4tlwr8ecc/Change-parameters-to-new-coordinate-system.paper?dl=0&rlkey=lotq1sh6wzkmyttisc05h0in0).

Hope these answer your questions.
